### ISSUE TITLE
Auto-serialization has issues

### ISSUE THREAD

**Issue by brstgt** [bzikarsky/react-gearman#20]
First, thanks for that project!

You do automagic (de-)serialization of data. IMHO this is not a good idea. The implementation should provide the pure transport logic and do not automagic things. Otherwise code using this library never knows if the payload has been deserialized already as you treat scalar results differently.
And your check if the data is already serialized is unnecessarily slow as you double serialize the data

Suggestion:
Remove automagic. The layer using that library has to decide how to serialize the data. (e.g. serialize vs json vs igbinary, ...)

**Comment by bzikarsky** [comment]
I'll agree. I stared at the the code for several minutes, trying to remember the reasoning behind this. Well, I don't. ;-)

I'll happily merge a PR with the removal of the serialization features.

**Comment by bzikarsky** [comment]
Fixed in #22
